---
image: danischm/nac:latest

stages:
  - validate
  - plan
  - deploy
  - destroy

variables:
  GIT_SSL_NO_VERIFY: "true"

  CC_USERNAME:
    description: "Cisco Catalyst Center Username"
  CC_PASSWORD:
    description: "Cisco Catalyst Center Password"
  CC_URL:
    description: "Cisco Catalyst Center URL"
  GITLAB_TOKEN:
    description: "User Access Token. Used to create comments on Merge Requests"
  TF_HTTP_USERNAME:
    description: "GitLab Username"
    value: "gitlab-ci-token"
  TF_HTTP_PASSWORD:
    description: "GitLab Access Token"
    value: "${CI_JOB_TOKEN}"
  GITLAB_API_URL:
    description: "GitLab API v4 root URL"
    value: "${CI_API_V4_URL}"
  TF_HTTP_ADDRESS:
    value: "${GITLAB_API_URL}/projects/${CI_PROJECT_ID}/terraform/state/mdo-catc"
  TF_HTTP_LOCK_ADDRESS:
    value: ${TF_HTTP_ADDRESS}/lock
  TF_HTTP_LOCK_METHOD:
    value: POST
  TF_HTTP_UNLOCK_ADDRESS:
    value: ${TF_HTTP_ADDRESS}/lock
  TF_HTTP_UNLOCK_METHOD:
    value: DELETE

before_script:
  - cd multi-domain/catc

cache:
  key: mdo_catc_terraform_modules
  paths:
    - multi-domain/catc/.terraform
    - multi-domain/catc/.terraform.lock.hcl
    - multi-domain/catc/defaults.yaml

validate:
  stage: validate
  script:
    - set -o pipefail && terraform fmt -check |& tee fmt_output.txt
    - set -o pipefail && nac-validate ./data/ |& tee validate_output.txt
  artifacts:
    paths:
      - multi-domain/catc/fmt_output.txt
      - multi-domain/catc/validate_output.txt
  cache: []
  rules:
    - if: $CI_COMMIT_TAG == null

plan:
  stage: plan
  resource_group: catc
  script:
    - terraform version
    - terraform init -upgrade -input=false
    - terraform plan -out=plan.tfplan -input=false
    - terraform show -no-color plan.tfplan > plan.txt
  artifacts:
    paths:
      - multi-domain/catc/plan.txt
      - multi-domain/catc/plan.tfplan
  needs:
    - validate
  only:
    - master
    - merge_requests
  except:
    - tags

deploy:
  stage: deploy
  resource_group: catc
  when: manual
  allow_failure: false
  script:
    - terraform apply -input=false -auto-approve plan.tfplan
  needs:
    - plan
  only:
    - master
    - merge_requests
  except:
    - tags

destroy:
  stage: destroy
  script:
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: "$CI_COMMIT_TAG =~ /^cleanup-mdo-catc/"
      when: always
