---
image:
  name: danischm/nac:latest
  pull_policy: always

stages:
  - validate
  - plan
  - deploy
  - destroy

variables:
  GIT_SSL_NO_VERIFY: "true"

  CC_USERNAME:
    description: "Cisco Catalyst Center Username"
  CC_PASSWORD:
    description: "Cisco Catalyst Center Password"
  CC_URL:
    description: "Cisco Catalyst Center URL"
  GITLAB_TOKEN:
    description: "User Access Token. Used to create comments on Merge Requests"
  TF_HTTP_USERNAME:
    description: "GitLab Username"
    value: "gitlab-ci-token"
  TF_HTTP_PASSWORD:
    description: "GitLab Access Token"
    value: "${GITLAB_TOKEN}"
  GITLAB_API_URL:
    description: "GitLab API v4 root URL"
    value: "${CI_API_V4_URL}"
  TF_HTTP_ADDRESS:
    value: "${GITLAB_API_URL}/projects/${CI_PROJECT_ID}/terraform/state/mdo-catc"
  TF_HTTP_LOCK_ADDRESS:
    value: "${TF_HTTP_ADDRESS}/lock"
  TF_HTTP_LOCK_METHOD:
    value: POST
  TF_HTTP_UNLOCK_ADDRESS:
    value: "${TF_HTTP_ADDRESS}/lock"
  TF_HTTP_UNLOCK_METHOD:
    value: DELETE

before_script:
  - update-ca-certificates
  - echo "http_proxy=$http_proxy"
  - echo "https_proxy=$https_proxy"
  - echo "NO_PROXY=$NO_PROXY"
  - echo "no_proxy=$no_proxy"
  - git config --global http.proxy "$http_proxy"
  - git config --global https.proxy "$https_proxy"
  - cd catc

cache:
  key: mdo_catc_terraform_modules
  paths:
    - catc/.terraform
    - catc/.terraform.lock.hcl
    - catc/defaults.yaml

validate:
  stage: validate
  script:
    - set -o pipefail && terraform fmt -check |& tee fmt_output.txt
    - set -o pipefail && nac-validate ./data/ |& tee validate_output.txt
  artifacts:
    paths:
      - catc/fmt_output.txt
      - catc/validate_output.txt
  cache: []
  rules:
    - if: $CI_COMMIT_TAG == null

plan:
  stage: plan
  resource_group: catc
  script:
    - terraform version
    - terraform init -upgrade -input=false
    - terraform plan -out=plan.tfplan -input=false
    - terraform show -no-color plan.tfplan > plan.txt
  artifacts:
    paths:
      - catc/plan.txt
      - catc/plan.tfplan
  needs:
    - validate
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^devhub\//'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^devhub\//'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
    - when: never

deploy:
  stage: deploy
  resource_group: catc
  when: manual
  allow_failure: false
  script:
    - terraform apply -input=false -auto-approve plan.tfplan
  needs:
    - plan
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^devhub\//'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^devhub\//'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never

destroy:
  stage: destroy
  resource_group: catc
  needs: []
  dependencies: []
  variables:
    TF_HTTP_PASSWORD: "${GITLAB_TOKEN}"
  script:
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^devhub\//'
      when: manual
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: true
