---
image:
  name: danischm/nac:latest
  pull_policy: always

stages:
  - validate
  - plan
  - deploy
  - destroy

variables:
  GIT_SSL_NO_VERIFY: "true"

  SDWAN_USERNAME:
    description: "Cisco SDWAN Username"
  SDWAN_PASSWORD:
    description: "Cisco SDWAN Password"
  SDWAN_URL:
    description: "Cisco SDWAN URL"
  GITLAB_TOKEN:
    description: "User Access Token. Used to create comments on Merge Requests"
  TF_HTTP_USERNAME:
    description: "GitLab Username"
    value: "gitlab-ci-token"
  TF_HTTP_PASSWORD:
    description: "GitLab Access Token"
    value: "${GITLAB_TOKEN}"
  GITLAB_API_URL:
    description: "GitLab API v4 root URL"
    value: "${CI_API_V4_URL}"
  TF_STATE_NAME:
    description: "Terraform state name (per branch)"
    value: "mdo-sdwan-${CI_COMMIT_REF_SLUG}"
  TF_HTTP_ADDRESS:
    value: "${GITLAB_API_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}"
  TF_HTTP_LOCK_ADDRESS:
    value: "${TF_HTTP_ADDRESS}/lock"
  TF_HTTP_LOCK_METHOD:
    value: POST
  TF_HTTP_UNLOCK_ADDRESS:
    value: "${TF_HTTP_ADDRESS}/lock"
  TF_HTTP_UNLOCK_METHOD:
    value: DELETE

before_script:
  - update-ca-certificates
  - cd sdwan

cache:
  key: mdo_sdwan_terraform_modules
  paths:
    - sdwan/.terraform
    - sdwan/.terraform.lock.hcl
    - sdwan/defaults.yaml

validate:
  stage: validate
  script:
    - set -o pipefail && terraform fmt -check |& tee fmt_output.txt
    - set -o pipefail && nac-validate ./data/ |& tee validate_output.txt
  artifacts:
    paths:
      - sdwan/fmt_output.txt
      - sdwan/validate_output.txt
    expire_in: 7 days
  cache: []
  rules:
    - if: $CI_COMMIT_TAG == null

plan:
  stage: plan
  resource_group: sdwan
  script:
    - terraform version
    - terraform init -upgrade -input=false
    - terraform plan -out=plan.tfplan -input=false
    - terraform show -no-color plan.tfplan > plan.txt
  artifacts:
    paths:
      - sdwan/plan.txt
      - sdwan/plan.tfplan
    expire_in: 7 days
  needs:
    - validate
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^devhub\//'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^devhub\//'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
    - when: never

deploy:
  stage: deploy
  resource_group: sdwan
  when: manual
  allow_failure: false
  script:
    - terraform apply -input=false -auto-approve plan.tfplan
  needs:
    - plan
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^devhub\//'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^devhub\//'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never

destroy:
  stage: destroy
  resource_group: sdwan
  needs: []
  dependencies: []
  variables:
    TF_HTTP_PASSWORD: "${GITLAB_TOKEN}"
  script:
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^devhub\//'
      when: manual
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: true
